# Generated by Django 4.0.6 on 2022-08-02 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('pwd', models.CharField(max_length=128)),
                ('username', models.CharField(max_length=128)),
                ('rdate', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
