# Generated by Django 4.0.6 on 2022-08-05 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world_cupapp', '0002_comment_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand_member',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('url', models.TextField()),
            ],
        ),
    ]
