# Generated by Django 4.0.6 on 2022-08-08 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world_cupapp', '0006_ranking_rank'),
    ]

    operations = [
        migrations.CreateModel(
            name='All_url',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('url', models.TextField()),
            ],
        ),
    ]
