# Generated by Django 4.0.6 on 2022-08-09 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world_cupapp', '0007_all_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='all_url',
            name='win_num',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
