# Generated by Django 4.0.6 on 2022-08-09 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world_cupapp', '0008_all_url_win_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment_test',
            fields=[
                ('comment_num', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=200)),
                ('theme', models.CharField(max_length=200)),
                ('comment', models.TextField()),
                ('hit_num', models.PositiveIntegerField(default=0)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
